#!/bin/sh

cd "$(dirname "$0")/.."

echo "=> Updating fixtures…" >&2

echo "==> Building test repository…" >&2
script/build-test-repository

VERSION=0.0.0-fixtures script/build

echo "==> Running git-metrics and updating output…" >&2
./git-metrics --no-progress --repository tmp/test-repository > fixtures/git-metrics.txt

echo "==> Removing non-deterministic rows…" >&2
script/remove-non-deterministic-rows fixtures/git-metrics.txt
